app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('tickets', 'TicketController');

app/Ticket.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ticket extends Model
{
    protected $table = 'tickets';

    protected $fillable = [
      'name' , 'description' , 'level'
    ];

    public function getLevelAttribute($value){
      if($value == 0){
        $valor = 'Bajo';
      }else if($value == 1){
        $valor = 'Medio';
      }elseif ($value == 2) {
        $valor = 'Urgente';
      }
      return $valor;
    }

    public function scopeLevel($query, $level){
      //dd("scope: ".$level);
      if ($level != "") {
        $query->where('level',$level);
      }
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TicketController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Ticket;
use Redirect;
use Session;
use Illuminate\Support\Facades\Validator;

class TicketController extends Controller
{
    public function index(Request $request){
      //dd($request->get('level'));
      $tickets   = Ticket::level($request->get('level'))->get();
      //$tickets = Ticket::All();
      return view('ticket.index' , compact('tickets'));
    }

    public function create(){
      return view('ticket.create');
    }

    public function store(Request $request){
      $rules = array(
          'name' => 'required|unique:tickets',
          'description' => 'required|min:5',
          'level' => 'required'
      );

      $validator = Validator::make($request->all() , $rules);

      if ($validator->fails()) {
         return redirect('tickets/create')->withErrors($validator)->withInput();
      } else {
        Ticket::create([
          'name'        => $request['name'],
          'description' => $request['description'],
          'level'       => $request['level']
        ]);

        Session::flash('status', 'El ticket ha sido creado satisfactoriamente!!');
        return Redirect::to('/tickets');
      }
    }

    public function edit($id){
      $ticket = Ticket::find($id);
      return view('ticket.edit' , compact('ticket'));
    }

    public function update(Request $request, $id){
      $ticket = Ticket::find($id);
      $ticket->fill($request->all());
      $ticket->save();

      Session::flash('status', 'El ticket ha sido actualizado satisfactoriamente!!');
      return Redirect::to('tickets');
    }

    public function destroy($id){
      Ticket::destroy($id);
      Session::flash('status','El Ticket seleccionado fue Eliminado');
      return Redirect::to('/tickets');
    }
}

resources/views/layouts/app.blade.php
<html lang="en"><head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Sistema Gestion de Tickets</title>

    <!-- Bootstrap core CSS -->
    <!-- Latest compiled and minified CSS -->
      {{ Html::script('jquery/jquery-2.2.3.min.js') }}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  {!!Html::style('semantic/semantic.min.css')!!}
  {!!Html::script('semantic/semantic.min.js')!!}



  </head>

  <body>

    <!-- Begin page content -->
    <div class="container">

      @yield('content')

    </div>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</body></html>

resources/views/ticket/alerts/errors.blade.php
<br>
@if(count($errors) > 0)
	<div class="alert alert-danger alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		<p><strong>Parece que tenemos algunos errores...</strong></p>
		<ul>
			@foreach($errors->all() as $error)
				<li>{!!$error!!}</li>
			@endforeach
		</ul>
	</div>
@endif

resources/views/ticket/create.blade.php
@extends('layouts.app')

@section('content')
  <div class="page-header">
    <h1>
      Crear Ticket
      <a class="ui button right floated" href="{!!URL::to('/tickets')!!}" >Cancelar</a>
			<button id="btn-save-ticket" class="ui primary button right floated">Guardar</button>
    </h1>
  </div>

  @include('ticket/alerts/errors')

  {{ Form::open(['route'=>'tickets.store','method'=>'POST', 'id'=>'form-create-ticket'])}}
    @include('ticket/forms/form')
  {{ Form::close() }}

  <script type="text/javascript">
    $('#btn-save-ticket').click(function(){
      $("#form-create-ticket").submit();
  });
  </script>
@endsection

resources/views/ticket/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="page-header">
      <h1>
        Editar Ticket
        <a class="ui button right floated" href="{!!URL::to('/tickets')!!}" >Cancelar</a>
			  <button id="btn-save-ticket" class="ui primary button right floated">Guardar</button>
      </h1>
    </div>

    {{ Form::model($ticket,['route'=>['tickets.update',$ticket->id] , 'method'=>'PUT', 'id'=>'form-edit-ticket']) }}
		 @include('ticket/forms/form')
	  {{ Form::close() }}

    <script type="text/javascript">
      $('#btn-save-ticket').click(function(){
        $("#form-edit-ticket").submit();
    });
    </script>
@endsection

resources/views/ticket/forms/form.blade.php
<div class="col-md-6">

    <div class="form-group">
      {{ Form::label('Nombre del Ticket')}}
      {{ Form::text('name',null,['class'=>'form-control']) }}
    </div>

    <div class="form-group">
      {{ Form::label('Descripcion del Ticket')}}
      @if(isset($ticket->description))
        <textarea class="form-control" name="description" rows="4" cols="40">{{ $ticket->description }}</textarea>
        @else
        <textarea class="form-control" name="description" rows="4" cols="40"></textarea>
      @endif

    </div>

    <div class="form-group">
      {{ Form::label('Importancia del Ticket')}}

      @if(isset($ticket->level))
          <select class="form-control" name="level">
        @if($ticket->level == 'Bajo')
            <option value="0" selected="">Bajo</option>
            <option value="1">Medio</option>
            <option value="2">Urgente</option>
        @elseif($ticket->level == 'Medio')
            <option value="0" >Bajo</option>
            <option value="1" selected="">Medio</option>
            <option value="2">Urgente</option>
        @elseif($ticket->level == 'Urgente')
            <option value="0" >Bajo</option>
            <option value="1">Medio</option>
            <option value="2"  selected="" >Urgente</option>
          </select>
        @endif

      @else
        <select class="form-control" name="level">
          <option selected="" disabled="">-- Seleccionar Nivel de importancia --</option>
          <option value="0">Bajo</option>
          <option value="1">Medio</option>
          <option value="2">Urgente</option>
        </select>
      @endif

    </div>
</div>

resources/views/ticket/index.blade.php
@extends('layouts.app')

@section('content')

  <div class="page-header">
        <h1>Listado de tickets
        {{ link_to_route('tickets.create', 'Crear Ticket','' , array('class' => 'ui primary button right floated')) }}
        </h1>
        {!!Html::script('js/buscador.js')!!}
  </div>

  @if(Session::has('status'))
		<div class="alert alert-success alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
			<p><strong>Acción realizada con Exito</strong> </p>
			<ul>
				<li>{{ Session::get('status') }}</li>
			</ul>
		</div>
	@endif

  <div class="col-sm-3 col-md-3 pull-right">
		<div class="form-group has-feedback">
	    <label class="control-label">Buscador</label>
	    <input type="text" class="form-control" id="buscar" onkeyup="buscador()" placeholder="Buscar..." />
	    <i class="glyphicon glyphicon-search form-control-feedback"></i>
		</div>
	</div>


  {{ Form::open(['route'=>'tickets.index' , 'method'=>'GET' , 'class'=>'pull-left']) }}
      <div class="form-group">
        <label class="sr-only">Nivel de importancia</label>
        <select class="form-control" name="level">
          <option selected="" disabled=""> Seleccionar Nivel</option>
          <option value="0"> Bajo </option>
            <option value="1"> Medio </option>
              <option value="2"> Urgente </option>
        </select>
      </div>
      <button type="submit" class="ui tiny primary button">Filtrar</button>
 {{ Form::close() }}



  <div class="content">

    <table class="table table-hover" id="tickets">
      <thead>
        <th>Nombre</th>
          <th>Descripcion</th>
            <th>Importacia</th>
              <th>Accion</th>
      </thead>
        @foreach($tickets as $ticket)
      <tbody>
          <td> {{ $ticket->name }} </td>
          <td> {{ $ticket->description }} </td>
          <td> {{ $ticket->level }}</td>
          <td>
					<a href="{{ route('tickets.edit', ['id' => $ticket->id]) }}" class="ui green button">Editar</a>
					</td>
					<td>
					{{ Form::open(['route' => ['tickets.destroy', $ticket->id ], 'method'=>'DELETE']) }}
						<button type="submit" class="ui red button" onclick="return confirm('Deseas eliminar este registro?')">Eliminar</button>
					{{ Form::close() }}
					</td>

      </tbody>
      @endforeach
    </table>

  </div>
@endsection